# Generated by Django 4.2.5 on 2024-11-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='名称', max_length=20, null=True, verbose_name='名称')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='内容', max_length=100, verbose_name='标题')),
                ('content', models.TextField(help_text='内容', verbose_name='内容')),
                ('read', models.IntegerField(help_text='阅读量', verbose_name='阅读量')),
                ('comment', models.IntegerField(help_text='评论数量', verbose_name='评论数量')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('type', models.ManyToManyField(help_text='新闻类型', to='news.newstype', verbose_name='新闻类型')),
            ],
        ),
    ]
