# Generated by Django 4.2.5 on 2024-11-23 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newstype_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '新闻表'},
        ),
        migrations.AlterModelOptions(
            name='newstype',
            options={'verbose_name': '新闻类型'},
        ),
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
    ]
