# Generated by Django 4.2.5 on 2024-11-23 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newstype_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='NewsInfo',
        ),
    ]
