# Generated by Django 4.2.5 on 2024-11-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_news_newsinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstype',
            name='name',
            field=models.CharField(blank=True, help_text='名称', max_length=20, null=True, verbose_name='新闻分类'),
        ),
    ]
