# Generated by Django 3.1 on 2024-11-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_newstype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newsinfo',
            name='type',
            field=models.ManyToManyField(help_text='新闻类型', to='news.NewsType', verbose_name='新闻类型'),
        ),
        migrations.AlterField(
            model_name='newstype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
