# Generated by Django 3.1 on 2024-11-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20241126_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsinfo',
            name='type',
            field=models.ManyToManyField(help_text='新闻类型', to='news.NewsType', verbose_name='新闻类型'),
        ),
    ]
