# Generated by Django 4.2.5 on 2024-11-24 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='图书名称')),
                ('read', models.IntegerField(default=0, verbose_name='阅读量')),
                ('comment', models.IntegerField(default=0, verbose_name='评论量')),
            ],
            options={
                'verbose_name': '图书',
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='人物名称')),
                ('gender', models.BooleanField(default=True, verbose_name='性别')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='所属图书')),
            ],
            options={
                'verbose_name': '人物',
                'db_table': 'person',
            },
        ),
    ]
